security:
    # Enable the new authenticator manager of Symfony
    enable_authenticator_manager: true

    # Set the password hasher we'll use for securing the passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Register a doctrine user provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Define our API firewall and configure it to use JWT for authentication
        api:
            pattern: ^/api/
            stateless: true
            provider: app_user_provider
            jwt: ~

        # Define our main firewall and configure it to use the JSON login method on the /token endpoint
        main:
            json_login:
                check_path: /token
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

    # Define some access control rules
    access_control:
      - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api/public, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api, roles: ROLE_USER }